version: '3.8'

services:

  mysql_db_server:
    image: mysql:latest
    container_name: mysql_db_server
    environment:
      - MYSQL_ROOT_PASSWORD=123
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin
    links:
      - mysql_db_server:db
    depends_on:
      - mysql_db_server
    environment:
      - PMA_HOST=db
      - MYSQL_ROOT_PASSWORD=123
    ports:
      - "8080:80"
